name: 'Setup Project'
description: 'Node.js setup'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '24.15.0'
  registry-url:
    description: 'Registry URL for publishing'
    required: false
    default: 'https://registry.npmjs.org'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: ${{ inputs.registry-url }}
